version: "3"
services:
  nginx:
    build:
      context: requirements/nginx/.
      args:
        DOMAIN_NAME: $DOMAIN_NAME
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/tools/localhost.crt:/etc/nginx/nginx.crt
      - ./requirements/nginx/tools/localhost.key:/etc/nginx/nginx.key
    container_name: nginx
        #mariadb:
        #build: mariadb/.
        #port:
        #- "3306:3306"
        #wordpress:
        #build: wordpress/.
        #port:
        #"9000:9000"
