version: "3"

services:
  https:
    image: "my_nginx:v01"
    restart: always
    build:
      context: requirements/nginx/.
      args:
        DOMAIN_NAME: $DOMAIN_NAME
    ports:
      - "443:443"
    volumes:
      - $CERTS_/localhost.crt:/etc/nginx/nginx.crt
      - $CERTS_/localhost.key:/etc/nginx/nginx.key
  backend:
    image: "my_mariadb:v01"
    restart: always
    build:
      context: requirements/mariadb/.
      args:
        MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
        MYSQL_USER: $MYSQL_USER
        MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - /home/alemarch/data/DB/:/var/lib/mysql
