version: "3.7"

services:

# NGINX
  web:
    image: "my_nginx:0.2"
    init: true
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - website:/var/www/html
    networks:
      - frontend
    depends_on:
      - front
    environment:
      DOMAIN_NAME:  $DOMAIN_NAME
      CERTS_:       $CERTS_
    build:
      context: requirements/nginx/.

# WORDPRESS
  front:
    image: "my_wordpress:0.1"
    restart: unless-stopped
    init: true
    ports:
      - "9000:9000"
    depends_on:
      - db
    volumes:
      - website:/var/www/html
      - database:/run/mysqld
    networks:
      - frontend
      - backend
    environment:
      DOMAIN_NAME:        $DOMAIN_NAME
      MYSQL_HOST:         $MYSQL_HOST
      MYSQL_USER:         $MYSQL_USER
      MYSQL_PASSWORD:     $MYSQL_PASSWORD
      WP_DBNAME:          $WP_DBNAME
      WP_TITLE:           $WP_TITLE
      WP_ADMIN:           $WP_ADMIN
      WP_ADMIN_PASSWORD:  $WP_ADMIN_PASSWORD
      WP_USER:            $WP_USER
      WP_USER_PASSWORD:   $WP_USER_PASSWORD
    build:
      context: requirements/wordpress/.

# MARIADB
  db:
    image: "my_mariadb:0.2"
    restart: unless-stopped
    init: true
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql
    networks:
      - backend
    environment:
      WP_DBNAME:            $WP_DBNAME
      WP_DB_HOST:    $MYSQL_HOST
      MYSQL_USER:           $MYSQL_USER
      MYSQL_PASSWORD:       $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD:  $MYSQL_ROOT_PASSWORD
    build:
      context: requirements/mariadb/.

networks:
  frontend:
  backend:

volumes:
  website:
      driver_opts:
        type: none
        device: $WP_VOLUME
        o: bind
  database:
      driver_opts:
        type: none
        device: $DB_VOLUME
        o: bind
