version: "3"
services:
  nginx:
    build:
      context: requirements/nginx/.
      args:
        DOMAIN_NAME: $DOMAIN_NAME
    ports:
      - "443:443"
    volumes:
      - $CERTS_/localhost.crt:/etc/nginx/nginx.crt
      - $CERTS_/localhost.key:/etc/nginx/nginx.key
    container_name: nginx
