version: "3"

services:
  web:
    image: "my_nginx:0.1"
    restart: always
    ports:
      - "443:443"
    volumes:
      - $CERTS_/localhost.crt:/etc/nginx/nginx.crt
      - $CERTS_/localhost.key:/etc/nginx/nginx.key
      - /home/alemarch/WordPress:/www
    networks:
      - frontend
    depends_on:
      - front
    build:
      context: requirements/nginx/.
      args:
        DOMAIN_NAME: $DOMAIN_NAME

  front:
    image: "my_wordpress:0.1"
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - db
    volumes:
      - /home/alemarch/data/WordPress/:/var/www/html
      - /home/alemarch/data/DB:/run/mysqld
    networks:
      - frontend
      - backend
    build:
      context: requirements/wordpress/.
      args:
        MYSQL_HOST: $MYSQL_HOST
        MYSQL_USER: $MYSQL_USER
        MYSQL_PASSWORD: $MYSQL_PASSWORD

  db:
    image: "my_mariadb:0.2"
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - $DB_VOLUME:/var/lib/mysql
    networks:
      - backend
    build:
      context: requirements/mariadb/.
      args:
        DB_VOLUME: $DB_VOLUME
        MYSQL_USER: $MYSQL_USER
        MYSQL_PASSWORD: $MYSQL_PASSWORD
        MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD

networks:
  frontend:
  backend:
